### PR TITLE
Add CI tests

### PR DESCRIPTION
**Pull request by jiro4989**
- Change `test` directory name to `tests`
  - Because `nimble test` requires `tests` directory
- Add docker environment for easy development
- Add CI test on GitHub Actions
  - [CI logs](https://github.com/jiro4989/exprgrad/runs/4212755499?check_suite_focus=true)

### CODE REVIEW

**Comment by can-lehmann** [comment]
Thank you for contributing to exprgrad! Let me preface my comment with the information that I have neither personally used docker nor GitHub Actions for any of my projects. I don't quite see the major benefits of having a docker environment at this (early) stage in the project. Especially since I neither have the knowledge to maintain it, nor the time to learn docker. Adding a GitHub Action to check for compatibility with multiple nim versions seems to be useful though.

It would be nice if the GitHub action would automatically mark pull requests with failing tests as non-mergable. I do not think that this is currently the case, since I use a custom unit-testing library for exprgrad. It does not return a different exit code depending on the success/failure of the tests. The preferred way to solve this would be to improve the unit-testing library.

Example for the issue (produced by adding `check false` to the equality test in `test_tensors.nim`; text after `#` symbols are comments added by me):

```
Test Failed: equality # Test failed
false: false

[✓] stringify
[✓] access
[✓] operators
[✓] matmul
[✓] transpose
[✓] view_last
[✓] select_samples
[✓] concat_last
[✓] reshape
   Success: Execution finished # Nimble reports success
   Success: All tests passed
```

**Comment by jiro4989** [comment]
Fixed.

```bash
/app # nimble test -Y
  Verifying dependencies for exprgrad@0.0.1
  Compiling /app/tests/test_model (from package exprgrad) using c backend
[✓] matmul
[✓] relu
[✓] mean_squared_error
[✓] transpose
[✓] extern
[✓] xor
   Success: Execution finished
  Verifying dependencies for exprgrad@0.0.1
  Compiling /app/tests/test_serialize (from package exprgrad) using c backend
[✓] scalar
[✓] composite
[✓] tensor
[✓] ir
   Success: Execution finished
  Verifying dependencies for exprgrad@0.0.1
  Compiling /app/tests/test_tensors (from package exprgrad) using c backend
[✓] equality
[✓] stringify

Test Failed: access
false: false

[✓] operators
[✓] matmul
[✓] transpose
[✓] view_last
[✓] select_samples
[✓] concat_last
[✓] reshape
Error: execution of an external program failed: '/app/tests/test_tensors '
       Tip: 3 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 1
        ... Command: /nim/bin/nim c --noNimblePath -d:NimblePkgVersion=0.0.1 --hints:off -r --path:. /app/tests/test_tensors
/app # echo $?
1
```

**Comment by can-lehmann** [comment]
Looks good! I assume that pull requests/commits will be marked correctly now, I guess we will see the next time someone contributes/I push to the repository. Exprgrad generally uses `snake_case` instead of `camelCase` for variable names and functions, please change `quitCode` to `quit_code` and `addExitProc` to `add_exit_proc`. Once this is done I plan on merging this PR.

**Comment by jiro4989** [comment]
Thanks. I fixed.

**Comment by can-lehmann** [comment]
Looks good!

**Pull request merged**
